type Sugar {
    some: String
}

type QuerySome {
    Some: String
}

type DubResult {
	message: String
}

input CreateBankAccountCommand{
    aggregateIdentifier: String
}

input DepositCommand{
    aggregateIdentifier: String
    amount: Float
}

input WithdrawalCommand{
    aggregateIdentifier: String
    amount: Float
}

type Query {
 	testMessage: Sugar
}

type Mutation {
	createBankAccount(createBankAccountCommand: CreateBankAccountCommand!): DubResult
	depositCommand(depositCommand: DepositCommand!): DubResult
	withdrawalCommand(withdrawalCommand: WithdrawalCommand!): DubResult
}

schema {
	query: Query
	mutation: Mutation
}
